camunda:
  bpm:
#    admin-user:
#      id: <admin_username>
#      password: <admin_password>
#      firstName: <admin_first_name>
    filter:
      create: Al
    auto-deployment-enabled: false
#    enabled: false
#    history-level: audit
spring:
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: localhost:2181
          brokers: localhost:9092
          auto-create-topics: false
        streams:
          binder:
            configuration:
              commit:
                interval:
                  ms: 1000
#  h2:
#    console:
#      enabled: true
